name: glowguide
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # google_sign_in: ^6.2.1

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.1
  dotted_border: ^3.1.0
  carousel_slider: ^5.1.2
  liquid_swipe: ^3.1.0
  intl_phone_field: ^3.2.0

  # State Management
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1

  # Networking
  dio: ^5.9.1

  # Storage (Local)
  shared_preferences: ^2.5.4

  # Media
  image_picker: ^1.2.1

  # Utilities
  flutter_screenutil: ^5.9.3
  intl: ^0.20.2
  url_launcher: ^6.3.2
  get_it: ^9.2.0
  internet_connection_checker_plus: ^2.9.1+2
  go_router: ^17.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  # hive_generator removed: using SharedPreferences for local favorites
  flutter_lints: ^6.0.0
  rename: ^3.1.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  change_app_package_name: ^1.5.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/backgrounds/
    - assets/images/icons/
    - assets/images/logos/
    - assets/images/others/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logos/logo.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#c0d9ed"
  image: assets/images/logos/logo.png
  fullscreen: true
