name: glowguide
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_sign_in: ^6.2.1

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  dotted_border: ^3.1.0
  carousel_slider: ^5.1.1
  liquid_swipe: ^3.1.0
  intl_phone_field: ^3.2.0

  # State Management
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1

  # Networking
  dio: ^5.9.0
  json_rpc_2: ^4.0.0

  # Storage (Local)
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path: ^1.9.1

  # Media
  image_picker: ^1.2.1

  # Utilities
  flutter_screenutil: ^5.9.3
  intl: ^0.20.2
  url_launcher: ^6.3.2
  connectivity_plus: ^7.0.0
  data_connection_checker_tv: ^0.3.5-nullsafety
  stack_trace: ^1.12.1
  get_it: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  flutter_lints: ^6.0.0
  rename: ^3.1.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.2
  change_app_package_name: ^1.5.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/backgrounds/
    - assets/images/icons/
    - assets/images/logos/
    - assets/images/others/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logos/logo.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logos/logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFit